source 'https://github.com/RisingSSR/RisingCyxbsSepc.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '11.0'

target 'RyScheduleCollectionViewLayoutOC_Example' do
  pod 'RyScheduleCollectionViewLayoutOC', :path => '../'

  target 'RyScheduleCollectionViewLayoutOC_Tests' do
    inherit! :search_paths

    
  end
end
